### PR TITLE
Made it simpler to work on vannot, cleaned the project structure and added a production ready docker runner.

### PR DESCRIPTION
**Pull request by JoepSchyns**
I removed browserify and the docker builder in favor of a webpack builder with build in webserver and hot reloading. With npm `run serve` you can now directly test out changes you made in vannot in your browser.

Secondly, I added a docker runner that both builds vannot and serves the project using nginx. With these changes a bit of the folder structure and some imports became obsolite, thus I took the liberty to clean up a little.

### CODE REVIEW

**Comment by issa-tseng** [comment]
the build process here was always sort of messy, i was not familiar with docker at the time (actually i'm still not really today). glad to see it get some cleaning up. i don't have any specific comments on anything i saw.

**Comment by JoepSchyns** [comment]
Cool! Good to hear. As far as I'm concerned the branch can be merged if you want.

**Comment by issa-tseng** [comment]
oh jeez! i seem to still have some rights over this repo but i haven’t really been in touch w the code owners in a while. i wonder if anyone from xyonix is watching this thread?

**Comment by zang0** [comment]
Watching. Issa feel free to do whatever you think is best.

**Comment by issa-tseng** [comment]
ah okay i spoke too soon, i can't merge this branch. but i think it's good to go.

**Pull request merged**
